#!/usr/bin/env bash
# ShiftYar deploy tool — ships the app to a Docker host over SSH.
#
#   deploy/deploy.sh [command]
#
# Commands
#   deploy      (default) test, sync, back up the DB, build/pull, start, health-check; auto-rollback on failure
#   setup       first-time nginx vhost + Let's Encrypt certificate for $DOMAIN
#   nginx       install/refresh only the nginx vhost (self-signed until `tls` runs)
#   tls         request the certificate with certbot
#   status      containers + health
#   logs        follow app logs
#   backup      dump PostgreSQL into $DEPLOY_DIR/backups
#   restore F   restore a backup file from $DEPLOY_DIR/backups (asks for confirmation)
#   rollback    switch back to the previously deployed image
#   credentials print the initial admin credentials stored on the server
#
# Settings come from the environment or deploy/deploy.env (see deploy.env.example).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
[[ -f "$ROOT/deploy/deploy.env" ]] && source "$ROOT/deploy/deploy.env"

HOST="${DEPLOY_HOST:-bazi-digital}"
DIR="${DEPLOY_DIR:-/opt/shiftyar}"
DOMAIN="${DOMAIN:-}"
APP_PORT="${APP_PORT:-8090}"
IMAGE="${IMAGE:-}"               # e.g. ghcr.io/bazi-digital/shiftyar:<sha>; empty = build on the server
KEEP_BACKUPS="${KEEP_BACKUPS:-14}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
GOPROXY_MIRROR="${GOPROXY:-}"   # Go module mirror for server-side builds (empty = official proxy)

COMPOSE="docker compose -p shiftyar -f $DIR/src/deploy/docker-compose.prod.yml --env-file $DIR/.env"

log()  { printf '\033[1;35m▸\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
remote() { ssh -o BatchMode=yes -o ConnectTimeout=15 "$HOST" "$@"; }

version() {
  local v
  v="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || date +%Y%m%d-%H%M%S)"
  if git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1 && [[ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null)" ]]; then
    v="$v-dirty"
  fi
  echo "$v"
}

need_domain() { [[ -n "$DOMAIN" ]] || die "Set DOMAIN (e.g. DOMAIN=shift.bazidigital.ir) in the environment or deploy/deploy.env"; }

preflight() {
  log "Checking $HOST"
  remote "docker compose version >/dev/null" || die "docker compose is not available on $HOST"
  ok "SSH and Docker OK"
}

run_tests() {
  if [[ "${SKIP_TESTS:-0}" == "1" ]]; then warn "Skipping tests (SKIP_TESTS=1)"; return; fi
  log "Running backend tests"
  (cd "$ROOT/backend" && go vet ./... && go test ./...) >/dev/null || die "Backend tests failed (run: cd backend && go test ./...)"
  log "Type-checking and building frontend"
  (cd "$ROOT/frontend" && npm run build) >/dev/null || die "Frontend build failed (run: cd frontend && npm run build)"
  ok "Tests passed"
}

sync_source() {
  log "Uploading source to $HOST:$DIR/src"
  tar -C "$ROOT" -czf - \
    --exclude=node_modules --exclude=dist --exclude=data --exclude='*.db' --exclude='*.db-*' \
    --exclude=.git --exclude=docs --exclude=deploy/deploy.env --exclude=.env \
    . | remote "set -e; mkdir -p $DIR; rm -rf $DIR/src.new; mkdir $DIR/src.new; tar -xzf - -C $DIR/src.new; rm -rf $DIR/src; mv $DIR/src.new $DIR/src"
  ok "Source uploaded"
}

# Creates $DIR/.env with random secrets on the first deploy only.
init_env() {
  remote "DIR=$DIR APP_PORT=$APP_PORT bash -s" <<'REMOTE'
set -euo pipefail
if [[ -f "$DIR/.env" ]]; then exit 0; fi
umask 077
mkdir -p "$DIR/backups"
admin_pw="$(openssl rand -base64 12 | tr -d '/+=')"
cat > "$DIR/.env" <<EOF
# Generated by deploy.sh on $(date -Is). Keep this file secret.
POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 32)
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$admin_pw
APP_PORT=$APP_PORT
EOF
printf 'username: admin\npassword: %s\n' "$admin_pw" > "$DIR/admin-credentials.txt"
echo "FIRST_DEPLOY"
REMOTE
}

cmd_backup() {
  log "Backing up database"
  remote "DIR=$DIR KEEP=$KEEP_BACKUPS COMPOSE='$COMPOSE' bash -s" <<'REMOTE'
set -euo pipefail
mkdir -p "$DIR/backups"
if [[ -z "$($COMPOSE ps -q postgres 2>/dev/null)" ]]; then echo "  (no database yet, nothing to back up)"; exit 0; fi
f="$DIR/backups/shiftyar-$(date +%Y%m%d-%H%M%S).sql.gz"
$COMPOSE exec -T postgres pg_dump -U shiftyar --clean --if-exists shiftyar | gzip > "$f"
chmod 600 "$f"
ls -1t "$DIR"/backups/shiftyar-*.sql.gz | tail -n +$((KEEP + 1)) | xargs -r rm -f
echo "  $(basename "$f") ($(du -h "$f" | cut -f1))"
REMOTE
  ok "Backup done"
}

wait_healthy() {
  local expect="${1:-}"
  log "Waiting for health check"
  remote "for i in \$(seq 1 45); do out=\$(curl -fsS http://127.0.0.1:$APP_PORT/api/health 2>/dev/null) && { echo \"\$out\"; exit 0; }; sleep 2; done; exit 1" >/tmp/shiftyar-health.$$ 2>&1 || { rm -f /tmp/shiftyar-health.$$; return 1; }
  local out; out="$(cat /tmp/shiftyar-health.$$)"; rm -f /tmp/shiftyar-health.$$
  if [[ -n "$expect" && "$out" != *"\"$expect\""* ]]; then
    warn "Healthy, but reports $out (expected $expect)"
  fi
  ok "Healthy: $out"
}

cmd_rollback() {
  log "Rolling back to the previous image"
  remote "set -e; docker image inspect shiftyar:previous >/dev/null 2>&1 || { echo 'no previous image'; exit 1; }; docker tag shiftyar:previous shiftyar:current; $COMPOSE up -d app"
  wait_healthy || die "Rollback is unhealthy too; check: deploy/deploy.sh logs"
  ok "Rolled back"
}

cmd_deploy() {
  local ver; ver="$(version)"
  log "Deploying ShiftYar $ver to $HOST"
  run_tests
  preflight
  sync_source
  if [[ "$(init_env)" == *FIRST_DEPLOY* ]]; then
    warn "First deploy: generated $DIR/.env with fresh secrets"
    FIRST=1
  fi
  cmd_backup

  remote "set -e; docker image inspect shiftyar:current >/dev/null 2>&1 && docker tag shiftyar:current shiftyar:previous || true"
  if [[ -n "$IMAGE" ]]; then
    log "Pulling $IMAGE"
    remote "set -e; docker pull '$IMAGE'; docker tag '$IMAGE' shiftyar:current"
  else
    log "Building image on $HOST (a few minutes on the first run)"
    # International links from the server can be flaky, so pull base images
    # and build with retries.
    remote "set -e
      for img in \$(awk '/^FROM/ {print \$2}' $DIR/src/Dockerfile | sort -u); do
        for i in 1 2 3 4 5; do docker pull -q \"\$img\" >/dev/null 2>&1 && break; echo \"  retrying pull of \$img (\$i)\"; sleep 3; done
      done
      cd $DIR/src
      for i in 1 2 3; do
        GOPROXY='$GOPROXY_MIRROR' SHIFTYAR_VERSION='$ver' $COMPOSE build app && exit 0
        echo '  build failed, retrying…'; sleep 5
      done
      exit 1"
  fi

  log "Starting containers"
  remote "set -e; $COMPOSE up -d --remove-orphans"
  if ! wait_healthy "$([[ -z "$IMAGE" ]] && echo "$ver")"; then
    warn "New version is unhealthy; recent logs:"
    remote "$COMPOSE logs --tail=40 app" || true
    cmd_rollback
    die "Deploy of $ver failed and was rolled back"
  fi
  remote "docker image prune -f >/dev/null" || true

  ok "Deployed $ver"
  if [[ "${FIRST:-0}" == "1" ]]; then
    printf '\n\033[1mInitial admin login\033[0m (also saved on the server in %s/admin-credentials.txt):\n' "$DIR"
    remote "cat $DIR/admin-credentials.txt"
    echo
    [[ -n "$DOMAIN" ]] && echo "Next: deploy/deploy.sh setup   # nginx + HTTPS for $DOMAIN"
  fi
  [[ -n "$DOMAIN" ]] && echo "→ https://$DOMAIN"
}

cmd_nginx() {
  need_domain
  local site="/etc/nginx/sites-available/$DOMAIN"
  local le="/etc/letsencrypt/live/$DOMAIN"
  local self="/etc/nginx/ssl/$DOMAIN-selfsigned"
  log "Installing nginx vhost for $DOMAIN → 127.0.0.1:$APP_PORT"
  # Use the Let's Encrypt certificate when present, otherwise a self-signed
  # placeholder (accepted by Cloudflare's "Full" mode) until `tls` runs.
  sed -e "s/__DOMAIN__/$DOMAIN/g" -e "s/__PORT__/$APP_PORT/g" "$ROOT/deploy/nginx/shiftyar.conf.template" |
    remote "set -e
      if [ -f '$le/fullchain.pem' ]; then cert='$le/fullchain.pem'; key='$le/privkey.pem'
      else
        cert='$self.crt'; key='$self.key'
        if [ ! -f \"\$cert\" ]; then
          mkdir -p /etc/nginx/ssl && chmod 700 /etc/nginx/ssl
          openssl req -x509 -nodes -newkey rsa:2048 -days 3650 -subj '/CN=$DOMAIN' -keyout \"\$key\" -out \"\$cert\" 2>/dev/null
        fi
      fi
      mkdir -p /var/www/letsencrypt
      tmp=\$(mktemp)
      sed -e \"s#__CERT__#\$cert#\" -e \"s#__KEY__#\$key#\" > \"\$tmp\"
      [ -e '$site' ] && cp -p '$site' '$site.bak'
      mv \"\$tmp\" '$site' && chmod 644 '$site'
      ln -sf '$site' '/etc/nginx/sites-enabled/$DOMAIN'
      if ! nginx -t 2>/tmp/shiftyar-nginx-test; then
        cat /tmp/shiftyar-nginx-test
        if [ -e '$site.bak' ]; then mv '$site.bak' '$site'; else rm -f '/etc/nginx/sites-enabled/$DOMAIN'; fi
        exit 1
      fi
      systemctl reload nginx
      echo \"  certificate: \$cert\""
  ok "nginx serves $DOMAIN"
}

cmd_tls() {
  need_domain
  log "Requesting a Let's Encrypt certificate for $DOMAIN"
  local email="--register-unsafely-without-email"
  [[ -n "$CERTBOT_EMAIL" ]] && email="-m $CERTBOT_EMAIL"
  # Webroot validation works behind Cloudflare: the challenge path is served
  # on both 80 and 443 by the vhost, whichever way the request arrives.
  remote "certbot certonly --webroot -w /var/www/letsencrypt -d '$DOMAIN' --non-interactive --agree-tos --keep-until-expiring $email --deploy-hook 'systemctl reload nginx'" ||
    die "certbot failed. Check that $DOMAIN resolves (directly or via Cloudflare in Full mode) and that 'deploy/deploy.sh nginx' ran first."
  cmd_nginx # switch the vhost to the new certificate
  ok "HTTPS enabled with Let's Encrypt: https://$DOMAIN"
}

cmd_restore() {
  local file="${1:-}"
  [[ -n "$file" ]] || { remote "ls -1t $DIR/backups/"; die "Usage: deploy/deploy.sh restore <file from the list above>"; }
  read -r -p "Replace the live database with $file? Type 'restore' to continue: " answer
  [[ "$answer" == "restore" ]] || die "Cancelled"
  cmd_backup
  log "Restoring $file"
  remote "set -e; gunzip -c '$DIR/backups/$(basename "$file")' | $COMPOSE exec -T postgres psql -q -U shiftyar -d shiftyar -v ON_ERROR_STOP=1 >/dev/null; $COMPOSE restart app"
  wait_healthy
  ok "Restored"
}

case "${1:-deploy}" in
  deploy)      cmd_deploy ;;
  setup)       cmd_nginx; cmd_tls ;;
  nginx)       cmd_nginx ;;
  tls)         cmd_tls ;;
  status)      remote "$COMPOSE ps"; wait_healthy ;;
  logs)        remote "$COMPOSE logs -f --tail=200 app" ;;
  backup)      cmd_backup ;;
  restore)     cmd_restore "${2:-}" ;;
  rollback)    cmd_rollback ;;
  credentials) remote "cat $DIR/admin-credentials.txt" ;;
  -h|--help|help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//' ;;
  *) die "Unknown command: $1 (see deploy/deploy.sh help)" ;;
esac
